const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

const USER_TYPES = {
  USER: "USER",
  WORKER: "WORKER",
  ADMIN: "ADMIN",
};

const BOOKING_STATUS = {
  IN_PROGRESS: "IN PROGRESS",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const BILL_STATUS = {
  PAID: "PAID",
  NOT_PAID: "NOT PAID",
};

module.exports = {
  HTTP_STATUS,
  USER_TYPES,
  BOOKING_STATUS,
  BILL_STATUS,
};
